server {
    server_name wip.computer www.wip.computer;

    root /var/www/wip.computer/public_html;
    index index.html index.htm;

    access_log /var/log/nginx/wip.computer.access.log;
    error_log /var/log/nginx/wip.computer.error.log;

    location / {
        autoindex off;
        try_files $uri $uri/ /index.html;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location ~ /\. {
        deny all;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/wip.computer/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wip.computer/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.wip.computer) {
        return 301 https://$host$request_uri;
    }

    if ($host = wip.computer) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;

    server_name wip.computer www.wip.computer;
    return 404;
}
